(let ((a (read)) (b (read)) (c (read)) (x (read)) (res 0))
  (dotimes (a (+ 1 a)) 
    (dotimes (b (+ 1 b))
      (dotimes (c (+ 1 c))
        (if (= (+ (* a 500) (* b 100) (* c 50)) x)
          (setq res (+ res 1))
        )
      )    
    )
  )
  (prin1 res)
)
